spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: usuario
    password: senha@senha
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: kafka:9092
    replicas: 1
    partitions: 10
    admin:
      auto-create-topics: true
    topic:
      product.update: product.update
    listener:
      concurrency: 10
    producer:
      max-block-ms: 5000
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    function:
      definition: orderPaidConsumer
    stream:
      bindings:
        orderPaidConsumer-in-0:
          destination: order.paid
          content-type: application/json
          group: stock-consumer
      kafka:
        binder:
          brokers: kafka:9092
          auto-create-topics: true
          consumer-properties:
            auto.offset.reset: earliest