spring:
  kafka:
    bootstrap-servers: localhost:9092
    replicas: 1
    partitions: 10
    admin:
      auto-create-topics: true
    topic:
      product.update: product.update
    listener:
      concurrency: 10
    producer:
      max-block-ms: 5000
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    function:
      definition: orderPaidConsumer
    stream:
      bindings:
        orderPaidConsumer-in-0:
          destination: order.paid
          content-type: application/json
          group: stock-consumer
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          consumer-properties:
            auto.offset.reset: earliest